# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# MOUSEKEY_ENABLE = no
# TAP_DANCE_ENABLE = yes
# SPACE_CADET_ENABLE = no

# OS_DETECTION_ENABLE = yes
# # KEY_OVERRIDE_ENABLE = yes
#
# TAP_DANCE_ENABLE = yes
# LAYER_LOCK_ENABLE = yes
# CAPS_WORD_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
